export type GamePhase =
  | 'NOT_STARTED'
  | 'DETERMINING_FIRST_PLAYER'
  | 'RESTORING_FIELD'
  | 'WAITING_FOR_ATTACK_CARD'
  | 'DRAWING_ATTACK_CARD'
  | 'WAITING_FOR_TARGET'
  | 'ENDING_TURN'
  | 'GAME_OVER';
