import Phaser from 'phaser';
import { FIELD_GOAL_AREA_HALF_HEIGHT, FIELD_GOAL_DEPTH } from './MatchFieldView';
import {
  MATCH_FIELD_CENTER_X,
  MATCH_FIELD_CENTER_Y,
  MATCH_FIELD_HEIGHT,
  MATCH_FIELD_WIDTH,
  MATCH_SCREEN_WIDTH
} from './matchScreenLayout';
import { SCOREBOARD_BACKGROUND_COLOR } from './scoreboardStyle';

export const MATCH_SIDE_PANEL_CORRIDOR_WIDTH = MATCH_FIELD_CENTER_X - MATCH_FIELD_WIDTH / 2 - FIELD_GOAL_DEPTH;
export const MATCH_SIDE_PANEL_LEFT_X = MATCH_SIDE_PANEL_CORRIDOR_WIDTH / 2;
export const MATCH_SIDE_PANEL_RIGHT_X = MATCH_SCREEN_WIDTH - MATCH_SIDE_PANEL_LEFT_X;
export const MATCH_SIDE_PANEL_TOP_Y = MATCH_FIELD_CENTER_Y - MATCH_FIELD_HEIGHT / 2;
export const MATCH_SIDE_PANEL_BOTTOM_Y = MATCH_FIELD_CENTER_Y - FIELD_GOAL_AREA_HALF_HEIGHT;
export const MATCH_SIDE_PANEL_WIDTH = MATCH_SIDE_PANEL_CORRIDOR_WIDTH - 8;
export const MATCH_SIDE_PANEL_HEIGHT = MATCH_SIDE_PANEL_BOTTOM_Y - MATCH_SIDE_PANEL_TOP_Y;
export const MATCH_SIDE_PANEL_CENTER_Y = MATCH_SIDE_PANEL_TOP_Y + MATCH_SIDE_PANEL_HEIGHT / 2;
export const MATCH_SIDE_PANEL_BACKGROUND_ALPHA = 0.82;
export const MATCH_SIDE_PANEL_BORDER_COLOR = 0x284438;
export const MATCH_SIDE_PANEL_BORDER_ALPHA = 0.8;
export const MATCH_SIDE_PANEL_HORIZONTAL_PADDING = 12;

export function createMatchSidePanelBackground(
  scene: Phaser.Scene,
  centerY: number
): Phaser.GameObjects.Rectangle {
  const background = scene.add.rectangle(
    0,
    centerY,
    MATCH_SIDE_PANEL_WIDTH,
    MATCH_SIDE_PANEL_HEIGHT,
    SCOREBOARD_BACKGROUND_COLOR,
    MATCH_SIDE_PANEL_BACKGROUND_ALPHA
  );
  background.setStrokeStyle(1, MATCH_SIDE_PANEL_BORDER_COLOR, MATCH_SIDE_PANEL_BORDER_ALPHA);

  return background;
}
