import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NATIONAL_TEAMS } from '../src/data/nationalTeams';
import { normalizeFlagCode } from '../src/data/flagCodes';

export const GENERATED_LOGO_REGISTRY_PATH = join('src', 'data', 'generated', 'availableTeamLogoFlagCodes.ts');

export function collectAvailableTeamLogoFlagCodes(projectRoot: string): string[] {
  const logoDir = join(projectRoot, 'public', 'logos');
  if (!existsSync(logoDir)) throw new Error('Logo directory not found: public/logos.');
  const knownCodes = new Set(NATIONAL_TEAMS.map((team) => team.flagCode));
  const codes = new Set<string>();
  for (const entry of readdirSync(logoDir, { withFileTypes: true })) {
    if (entry.name === 'README.md' && entry.isFile()) continue;
    if (!entry.isFile()) throw new Error(`Unexpected logo directory entry: ${entry.name}.`);
    const filename = entry.name;
    if (!filename.endsWith('.webp')) throw new Error(`Expected .webp logo filename, found "${filename}".`);
    const code = filename.slice(0, -5);
    const logicalCode = normalizeFlagCode(code.toLowerCase());
    if (codes.has(logicalCode)) throw new Error(`Duplicate logical logo code: ${logicalCode}.`);
    if (code !== logicalCode) throw new Error(`Non-canonical logo filename "${filename}"; expected "${logicalCode}.webp".`);
    if (!knownCodes.has(code)) throw new Error(`unknown logo code: ${code}`);
    codes.add(code);
  }
  return [...codes].sort();
}

export function syncLogoRegistry(options: { projectRoot?: string; write?: boolean } = {}) {
  const projectRoot = options.projectRoot ?? process.cwd();
  const flagCodes = collectAvailableTeamLogoFlagCodes(projectRoot);
  const generatedPath = join(projectRoot, GENERATED_LOGO_REGISTRY_PATH);
  const content = [
    '// This file is generated by scripts/sync-logo-registry.ts.',
    '// Add canonical public/logos/<flagCode>.webp files and run npm run sync:logos.',
    'export const AVAILABLE_TEAM_LOGO_FLAG_CODES = [',
    flagCodes.map((code) => `  '${code}'`).join(',\n'),
    '] as const;',
    ''
  ].join('\n');
  if ((options.write ?? true) && (!existsSync(generatedPath) || readFileSync(generatedPath, 'utf8') !== content)) {
    mkdirSync(dirname(generatedPath), { recursive: true });
    writeFileSync(generatedPath, content, 'utf8');
  }
  return { flagCodes, generatedPath, content };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    const result = syncLogoRegistry();
    console.log(`Synced ${GENERATED_LOGO_REGISTRY_PATH} with ${result.flagCodes.length} team logos.`);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
