import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NATIONAL_TEAMS } from '../src/data/nationalTeams';

export const RESERVED_KIT_FILE_BASENAMES = ['none', 'gk1', 'gk2'] as const;
export const GENERATED_KIT_REGISTRY_PATH = join(
  'src',
  'data',
  'generated',
  'availableManualKitFlagCodes.ts'
);

export type SyncKitRegistryOptions = {
  projectRoot?: string;
  write?: boolean;
};

export type SyncKitRegistryResult = {
  flagCodes: string[];
  awayFlagCodes: string[];
  generatedPath: string;
  content: string;
};

const WEBP_EXTENSION = '.webp';
const RESERVED_KIT_FILE_BASENAME_SET = new Set<string>(RESERVED_KIT_FILE_BASENAMES);

export function syncKitRegistry(options: SyncKitRegistryOptions = {}): SyncKitRegistryResult {
  const projectRoot = options.projectRoot ?? process.cwd();
  const write = options.write ?? true;
  const flagCodes = collectAvailableManualKitFlagCodes(projectRoot);
  const generatedPath = join(projectRoot, GENERATED_KIT_REGISTRY_PATH);
  const awayFlagCodes = collectAvailableManualKitFlagCodes(projectRoot, 'away');
  const content = renderGeneratedKitRegistry(flagCodes, awayFlagCodes);

  if (write) {
    mkdirSync(dirname(generatedPath), { recursive: true });
    writeFileSync(generatedPath, content, 'utf8');
  }

  return {
    flagCodes,
    awayFlagCodes,
    generatedPath,
    content
  };
}

export function collectAvailableManualKitFlagCodes(projectRoot: string, variant: 'home' | 'away' = 'home'): string[] {
  const kitImageDir = join(projectRoot, 'public', 'kits', 'images');

  if (!existsSync(kitImageDir)) {
    throw new Error(`Kit image directory not found: ${formatRelativePath(projectRoot, kitImageDir)}`);
  }

  const nationalFlagCodeSet = new Set(NATIONAL_TEAMS.map((team) => team.flagCode));
  const flagCodes: string[] = [];

  for (const entry of readdirSync(kitImageDir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const fileName = entry.name;
    if (!fileName.endsWith(WEBP_EXTENSION)) {
      continue;
    }

    const basename = fileName.slice(0, -WEBP_EXTENSION.length);
    if (RESERVED_KIT_FILE_BASENAME_SET.has(basename)) continue;
    const match = /^(.*)([12])$/.exec(basename);
    const flagCode = match?.[1] ?? basename;

    if (match === null || !nationalFlagCodeSet.has(flagCode)) {
      throw new Error(
        `Unknown kit file ${formatRelativePath(
          projectRoot,
          join(kitImageDir, fileName)
        )}: "${flagCode}" is not a national team flagCode.\nRename the file or add the team first.`
      );
    }

    if (match[2] === (variant === 'home' ? '1' : '2')) flagCodes.push(flagCode);
  }

  return [...new Set(flagCodes)].sort();
}

export function renderGeneratedKitRegistry(flagCodes: readonly string[], awayFlagCodes: readonly string[] = []): string {
  const rows = flagCodes.map((flagCode) => `  '${flagCode}'`).join(',\n');

  return [
    '// This file is generated by scripts/sync-kit-registry.ts.',
    '// Do not edit it manually. Add public/kits/images/<flagCode>1.webp or <flagCode>2.webp and run npm run sync:kits.',
    'export const AVAILABLE_MANUAL_KIT_FLAG_CODES = [',
    rows,
    '] as const;',
    'export const AVAILABLE_AWAY_KIT_FLAG_CODES = [',
    awayFlagCodes.map((code) => `  '${code}'`).join(',\n'),
    '] as const;',
    ''
  ].join('\n');
}

function formatRelativePath(projectRoot: string, path: string): string {
  return relative(projectRoot, path).replace(/\\/g, '/');
}

async function runCli(): Promise<void> {
  const result = syncKitRegistry();
  const relativeGeneratedPath = formatRelativePath(process.cwd(), result.generatedPath);

  console.log(
    `Synced ${relativeGeneratedPath} with ${result.flagCodes.length} HOME and ${result.awayFlagCodes.length} AWAY kit(s).`
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
